# Generated by Django 6.0.5 on 2026-05-15 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('max_orders', models.PositiveIntegerField(default=30)),
                ('current_orders', models.PositiveIntegerField(default=0)),
                ('slot_status', models.CharField(choices=[('open', 'Open'), ('full', 'Full'), ('closed', 'Closed')], default='open', max_length=20)),
            ],
            options={
                'ordering': ['slot_date', 'start_time'],
            },
        ),
    ]
