# Generated by Django 6.0.5 on 2026-05-27 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_present',
            field=models.BooleanField(default=True),
        ),
    ]
