# Generated by Django 6.0.5 on 2026-05-15 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QueueLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('queue_position', models.PositiveIntegerField(default=0)),
                ('estimated_wait', models.PositiveIntegerField(default=0)),
                ('logged_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queue_logs', to='orders.order')),
            ],
            options={
                'ordering': ['-logged_at'],
            },
        ),
    ]
