# Generated by Django 6.0.3 on 2026-05-28 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queue_engine', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QueueState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rush_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('heavy', 'Heavy')], default='medium', max_length=10)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Queue State',
                'verbose_name_plural': 'Queue States',
            },
        ),
    ]
