# Generated by Django 6.0.5 on 2026-05-15 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='category',
            field=models.CharField(choices=[('breakfast', 'Breakfast'), ('brunch', 'Brunch'), ('lunch', 'Lunch'), ('evening snacks', 'Evening Snacks'), ('snacks', 'Snacks'), ('chaat', 'Chaat Items'), ('beverages', 'Beverages'), ('juices', 'Fresh Juices'), ('desserts', 'Desserts'), ('bites', 'Fast Food & Bites'), ('chinese', 'Chinese')], default='lunch', max_length=50),
        ),
    ]
