# Generated by Django 6.0.3 on 2026-05-19 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_alter_menuitem_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='is_veg',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='category',
            field=models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('evening_snacks', 'Evening Snacks'), ('chaat', 'Chaat'), ('beverages', 'Beverages'), ('juices', 'Juices'), ('desserts', 'Desserts'), ('bites', 'Bites'), ('chinese', 'Chinese'), ('pizza', 'Pizza'), ('burgers', 'Burgers'), ('parotta', 'Parotta'), ('roti', 'Roti & Naan')], default='lunch', max_length=50),
        ),
    ]
