# Generated by Django 6.0.5 on 2026-05-27 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_menuitem_is_veg_alter_menuitem_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='category',
            field=models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('evening_snacks', 'Snacks'), ('chaat', 'Chaat'), ('beverages', 'Refreshing Drinks'), ('juices', 'Juices'), ('desserts', 'Desserts'), ('bites', 'Bites'), ('chinese', 'Chinese'), ('pizza', 'Pizza'), ('burgers', 'Burgers'), ('parotta', 'Parotta'), ('roti', 'Roti & Naan')], default='lunch', max_length=50),
        ),
    ]
