# Generated by Django 6.0.5 on 2026-05-27 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_alter_menuitem_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='food_type',
            field=models.CharField(choices=[('veg', 'Veg'), ('egg', 'Egg'), ('non_veg', 'Non-Veg')], default='veg', max_length=20),
        ),
    ]
