# Generated by Django 6.0.3 on 2026-05-27 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_menuitem_food_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='combo_items',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='category',
            field=models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('evening_snacks', 'Snacks'), ('chaat', 'Chaat'), ('beverages', 'Refreshing Drinks'), ('juices', 'Juices'), ('desserts', 'Desserts'), ('bites', 'Bites'), ('chinese', 'Chinese'), ('pizza', 'Pizza'), ('burgers', 'Burgers'), ('parotta', 'Parotta'), ('roti', 'Roti & Naan'), ('combo', 'Combo Meal')], default='lunch', max_length=50),
        ),
    ]
